NAUKA_TASKS = [
    "Przeczytać rozdział z książki naukowej",
    "Rozwiązać zadania z matematyki",
    "Nauczyć się 20 nowych słówek z języka obcego",
    "Przygotować notatki z wykładu",
    "Przeprowadzić eksperyment naukowy",
    "Napisać esej na temat historyczny",
    "Obejrzeć dokument naukowy",
    "Przygotować prezentację z fizyki",
    "Rozwiązać quiz z chemii",
    "Przeanalizować dane statystyczne",
    "Przestudiować mapę geologiczną",
    "Nauczyć się wzorów matematycznych",
    "Przeczytać artykuł naukowy",
    "Przygotować się do kolokwium",
    "Rozwiązać zadania z programowania",
    "Przeprowadzić research naukowy",
    "Nauczyć się tablicy Mendelejewa",
    "Przeanalizować tekst literacki",
    "Przygotować projekt badawczy",
    "Rozwiązać krzyżówkę tematyczną",
    "Opanować nową teorię naukową",
    "Przeczytać biografię naukowca",
    "Przygotować raport z obserwacji",
    "Nauczyć się zasad logiki",
    "Rozwiązać zadania z genetyki",
    "Przestudiować schemat anatomiczny",
    "Przygotować się do olimpiady przedmiotowej",
    "Przeanalizować wykresy i dane",
    "Nauczyć się dat historycznych",
    "Rozwiązać test z geografii",
    "Przeczytać pracę dyplomową",
    "Przygotować konspekt wykładu",
    "Opanować terminologię specjalistyczną",
    "Rozwiązać łamigłówkę logiczną",
    "Przestudiować case study",
    "Nauczyć się skali muzycznej",
    "Przygotować recenzję artykułu",
    "Rozwiązać zadania z ekonomii",
    "Przeczytać podręcznik akademicki",
    "Przeanalizować dane meteorologiczne",
    "Nauczyć się systemu klasyfikacji",
    "Przygotować bibliografię",
    "Rozwiązać test psychologiczny",
    "Przestudiować metodologię badań",
    "Opanować nową technikę uczenia",
    "Przygotować się do egzaminu",
    "Rozwiązać zadania z robotyki",
    "Przeczytać monografię naukową",
    "Przeanalizować dane demograficzne",
    "Nauczyć się teorii ewolucji"
]

SPORT_TASKS = [
    "Przebiec 5 km",
    "Wykonać trening siłowy",
    "Pojeździć na rowerze 10 km",
    "Wykonać rozciąganie całego ciała",
    "Pograć w piłkę nożną",
    "Popływać na basenie",
    "Wykonać trening interwałowy",
    "Poćwiczyć jogę",
    "Pójść na spacer Nordic Walking",
    "Wykonać trening ABS",
    "Pograć w koszykówkę",
    "Pojeździć na rolkach",
    "Wykonać trening cardio",
    "Poćwiczyć na siłowni zewnętrznej",
    "Pograć w tenisa",
    "Wykonać trening funkcjonalny",
    "Pójść na trening bokserski",
    "Pojeździć na deskorolce",
    "Wykonać trening obwodowy",
    "Pograć w siatkówkę",
    "Poćwiczyć kalistenikę",
    "Wykonać marszobieg",
    "Pójść na zajęcia fitness",
    "Pojeździć na nartach biegowych",
    "Wykonać trening wytrzymałościowy",
    "Pograć w badmintona",
    "Poćwiczyć sztuki walki",
    "Wykonać trening mobilności",
    "Pójść na wspinaczkę",
    "Pojeździć na łyżwach",
    "Wykonać trening core",
    "Pograć w golfa",
    "Poćwiczyć z taśmami oporowymi",
    "Wykonać trening metaboliczny",
    "Pójść na jogging",
    "Pojeździć na hulajnodze",
    "Wykonać trening plyometryczny",
    "Pograć w squasha",
    "Poćwiczyć pilates",
    "Wykonać trening obciążeniowy",
    "Pójść na pływanie synchroniczne",
    "Pojeździć konno",
    "Wykonać trening wydolnościowy",
    "Pograć w rugby",
    "Poćwiczyć tai chi",
    "Wykonać trening stabilizacji",
    "Pójść na aqua aerobik",
    "Pojeździć na waveboardzie",
    "Wykonać trening koordynacji",
    "Pograć w baseball"
]

